package pl.detailing.crm.signing

import jakarta.servlet.http.HttpServletRequest
import kotlinx.coroutines.runBlocking
import org.springframework.http.HttpHeaders
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.transaction.annotation.Transactional
import org.springframework.web.bind.annotation.*
import pl.detailing.crm.protocol.infrastructure.S3ProtocolStorageService
import pl.detailing.crm.shared.*
import pl.detailing.crm.signing.domain.SignatureAuditEventType
import pl.detailing.crm.signing.infrastructure.*
import java.time.Instant

/**
 * Session-free controller for the signing tablet mounted in front of the customer.
 *
 * Authentication is performed exclusively via the [X-Tablet-Token] header (Redis) —
 * the same trust model as the mobile QR upload endpoints. Tenant isolation is enforced
 * by reading tenantId ONLY from the Redis token metadata, never from the request.
 *
 * Tablet app contract (WYSIWYS loop):
 *  1. GET  /signature-requests/pending      → request metadata + single-use challenge
 *  2. GET  /signature-requests/{id}/document → EXACT PDF bytes (hash in X-Document-Sha256);
 *     the tablet renders these bytes, computes its own SHA-256 over them and keeps it.
 *  3. Customer reads the document, ticks the declaration checkbox, draws the signature
 *     on a TRANSPARENT canvas (PNG with alpha — never a white background), taps "Gotowe".
 *  4. POST /signature-requests/{id}/submit  → {signature PNG (base64), tablet-side hash,
 *     challenge, declarationAccepted, timestamps}. The tablet MUST then discard the
 *     signature bitmap and document from its local cache.
 */
@RestController
@RequestMapping("/api/tablet")
class TabletSignatureController(
    private val tabletSessionService: TabletSessionService,
    private val signatureRequestRepository: SignatureRequestRepository,
    private val submitSignatureHandler: SubmitSignatureHandler,
    private val lifecycleService: SignatureRequestLifecycleService,
    private val s3StorageService: S3ProtocolStorageService,
    private val documentIntegrityService: DocumentIntegrityService,
    private val auditTrailService: SignatureAuditTrailService,
    private val eventPublisher: SignatureEventPublisher
) {

    /**
     * Exchange a one-time pairing code (generated by an employee in the CRM)
     * for a long-lived device token.
     *
     * POST /api/tablet/pair   { "pairingCode": "123456", "deviceName": "Recepcja 1" }
     */
    @PostMapping("/pair")
    fun pair(@RequestBody request: TabletPairRequest): ResponseEntity<TabletPairResponse> {
        if (request.pairingCode.isBlank() || request.deviceName.isBlank()) {
            throw ValidationException("Kod parowania i nazwa urządzenia są wymagane")
        }
        val paired = tabletSessionService.pairTablet(request.pairingCode.trim(), request.deviceName.trim())
            ?: throw ForbiddenException("Nieprawidłowy lub wygasły kod parowania")

        eventPublisher.publishTabletEvent(
            tenantId = paired.tenantId,
            tabletId = paired.tabletId,
            deviceName = request.deviceName.trim(),
            eventType = "TABLET_PAIRED"
        )

        return ResponseEntity.status(HttpStatus.CREATED).body(
            TabletPairResponse(tabletId = paired.tabletId, token = paired.token, studioId = paired.tenantId)
        )
    }

    /**
     * Validate the stored device token and return the tablet's context.
     * Called on app start (day-2 auto-reconnect): a 200 means the token is still valid
     * (its TTL was just refreshed); a 403 means the tablet must be paired again.
     *
     * GET /api/tablet/context
     * X-Tablet-Token: <token>
     */
    @GetMapping("/context")
    fun getContext(
        @RequestHeader("X-Tablet-Token") token: String
    ): ResponseEntity<TabletContextResponse> {
        val session = authenticate(token)
        return ResponseEntity.ok(
            TabletContextResponse(
                tabletId = session.tabletId,
                studioId = session.tenantId,
                deviceName = session.deviceName
            )
        )
    }

    /**
     * The active signing session routed to this tablet (or any tablet in the studio).
     * Returns 204 when nothing is waiting. The response includes the single-use
     * challenge that MUST be echoed on submit.
     */
    @GetMapping("/signature-requests/pending")
    fun getPendingRequest(
        @RequestHeader("X-Tablet-Token") token: String
    ): ResponseEntity<TabletSignatureRequestDto> {
        val session = authenticate(token)

        val now = Instant.now()
        val pending = signatureRequestRepository
            .findActiveForTablet(java.util.UUID.fromString(session.tenantId), session.tabletId, now)
            .firstOrNull()
            ?: return ResponseEntity.noContent().build()

        val request = pending.toDomain()
        val challenge = documentIntegrityService.peekChallenge(request.id.value)
            ?: return ResponseEntity.noContent().build() // challenge expired → session unusable

        return ResponseEntity.ok(
            TabletSignatureRequestDto(
                requestId = request.id.toString(),
                documentName = request.documentName,
                signerName = request.signerName,
                declarationText = request.declarationText,
                documentSha256 = request.documentSha256,
                challenge = challenge,
                expiresAt = request.expiresAt,
                documentUrl = "/api/tablet/signature-requests/${request.id}/document"
            )
        )
    }

    /**
     * Stream the EXACT PDF bytes awaiting signature.
     *
     * WYSIWYS enforcement at delivery time: the bytes are re-hashed as they leave the
     * server and compared with the digest computed when the request was created —
     * if the stored object changed in the meantime, delivery is refused.
     * The digest is exposed in the X-Document-Sha256 header so the tablet can verify
     * what it received and later echo the hash on submit.
     */
    @GetMapping("/signature-requests/{requestId}/document")
    @Transactional
    fun getDocument(
        @RequestHeader("X-Tablet-Token") token: String,
        @PathVariable requestId: String,
        httpRequest: HttpServletRequest
    ): ResponseEntity<ByteArray> {
        val session = authenticate(token)
        val request = loadRequestForTablet(session, requestId)

        if (request.isExpired()) {
            lifecycleService.markExpired(request)
            throw ValidationException("Żądanie podpisu wygasło")
        }
        if (request.isTerminal()) {
            throw ConflictException("Żądanie podpisu zostało już zakończone")
        }

        val pdfBytes = s3StorageService.downloadBytes(request.documentS3Key)
        val actualSha256 = documentIntegrityService.sha256Hex(pdfBytes)
        if (!documentIntegrityService.digestsMatch(request.documentSha256, actualSha256)) {
            throw ConflictException("Integralność dokumentu została naruszona — dokument nie zostanie wyświetlony")
        }

        val displayed = request.markDisplayed()
        signatureRequestRepository.save(SignatureRequestEntity.fromDomain(displayed))

        auditTrailService.append(
            requestId = request.id.value,
            studioId = request.studioId.value,
            eventType = SignatureAuditEventType.DOCUMENT_DELIVERED,
            actor = "TABLET ${session.tabletId} (${session.deviceName})",
            ipAddress = clientIp(httpRequest),
            userAgent = httpRequest.getHeader(HttpHeaders.USER_AGENT),
            details = "sha256=$actualSha256 — zgodność z żądaniem potwierdzona przy dostarczeniu"
        )
        eventPublisher.publish(
            tenantId = request.studioId.value.toString(),
            requestId = request.id.toString(),
            eventType = "SIGNATURE_DISPLAYED",
            tabletId = session.tabletId,
            documentName = request.documentName,
            signerName = request.signerName,
            status = displayed.status.name
        )

        return ResponseEntity.ok()
            .contentType(MediaType.APPLICATION_PDF)
            .header("X-Document-Sha256", actualSha256)
            .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"document.pdf\"")
            .header(HttpHeaders.CACHE_CONTROL, "no-store")
            .body(pdfBytes)
    }

    /**
     * Submit the signature packet: [obraz podpisu + hash wyświetlonego dokumentu + czas].
     * See [SubmitSignatureHandler] for the verification pipeline.
     */
    @PostMapping("/signature-requests/{requestId}/submit")
    fun submitSignature(
        @RequestHeader("X-Tablet-Token") token: String,
        @PathVariable requestId: String,
        @RequestBody body: TabletSubmitSignatureRequest,
        httpRequest: HttpServletRequest
    ): ResponseEntity<TabletSubmitSignatureResponse> = runBlocking {
        val session = authenticate(token)

        if (body.signatureImageBase64.isBlank()) {
            throw ValidationException("Obraz podpisu jest wymagany")
        }
        if (body.documentSha256.isBlank() || body.challenge.isBlank()) {
            throw ValidationException("Brak danych integralności dokumentu (hash/challenge)")
        }

        val result = submitSignatureHandler.handle(
            SubmitSignatureCommand(
                studioId = StudioId(java.util.UUID.fromString(session.tenantId)),
                requestId = SignatureRequestId.fromString(requestId),
                tabletId = session.tabletId,
                deviceName = session.deviceName,
                documentSha256 = body.documentSha256.trim(),
                challenge = body.challenge,
                declarationAccepted = body.declarationAccepted,
                declarationAcceptedAt = body.declarationAcceptedAt,
                signatureImageBase64 = body.signatureImageBase64,
                ipAddress = clientIp(httpRequest),
                userAgent = httpRequest.getHeader(HttpHeaders.USER_AGENT)
            )
        )

        ResponseEntity.ok(
            TabletSubmitSignatureResponse(
                requestId = result.requestId.toString(),
                status = result.status.name,
                sealApplied = result.sealApplied,
                timestampApplied = result.timestampApplied
            )
        )
    }

    /** Customer refuses to sign. */
    @PostMapping("/signature-requests/{requestId}/decline")
    fun declineSignature(
        @RequestHeader("X-Tablet-Token") token: String,
        @PathVariable requestId: String,
        @RequestBody(required = false) body: TabletDeclineRequest?,
        httpRequest: HttpServletRequest
    ): ResponseEntity<TabletSubmitSignatureResponse> {
        val session = authenticate(token)
        val declined = lifecycleService.decline(
            studioId = StudioId(java.util.UUID.fromString(session.tenantId)),
            requestId = SignatureRequestId.fromString(requestId),
            tabletId = session.tabletId,
            reason = body?.reason,
            ipAddress = clientIp(httpRequest),
            userAgent = httpRequest.getHeader(HttpHeaders.USER_AGENT)
        )
        return ResponseEntity.ok(
            TabletSubmitSignatureResponse(
                requestId = declined.id.toString(),
                status = declined.status.name,
                sealApplied = false,
                timestampApplied = false
            )
        )
    }

    private fun authenticate(token: String): TabletSession =
        tabletSessionService.validateToken(token)
            ?: throw ForbiddenException("Nieprawidłowy lub wygasły token tabletu")

    private fun loadRequestForTablet(
        session: TabletSession,
        requestId: String
    ): pl.detailing.crm.signing.domain.SignatureRequest {
        val entity = signatureRequestRepository.findByIdAndStudioId(
            SignatureRequestId.fromString(requestId).value,
            java.util.UUID.fromString(session.tenantId)
        ) ?: throw NotFoundException("Żądanie podpisu nie zostało znalezione")
        val request = entity.toDomain()
        if (request.tabletId != null && request.tabletId != session.tabletId) {
            throw ForbiddenException("Żądanie podpisu jest przypisane do innego tabletu")
        }
        return request
    }

    private fun clientIp(request: HttpServletRequest): String =
        request.getHeader("X-Forwarded-For")?.split(",")?.firstOrNull()?.trim()
            ?: request.remoteAddr
}

// ==================== DTOs ====================

data class TabletPairRequest(
    val pairingCode: String,
    val deviceName: String
)

data class TabletPairResponse(
    val tabletId: String,
    val token: String,
    /** Needed by the tablet to subscribe to /topic/studio.{studioId}.tablet.signature */
    val studioId: String
)

data class TabletContextResponse(
    val tabletId: String,
    val studioId: String,
    val deviceName: String
)

data class TabletSignatureRequestDto(
    val requestId: String,
    val documentName: String,
    val signerName: String,
    val declarationText: String,
    /** Expected SHA-256 — the tablet must verify the downloaded bytes against it. */
    val documentSha256: String,
    /** Single-use anti-replay nonce; must be echoed on submit. */
    val challenge: String,
    val expiresAt: Instant,
    val documentUrl: String
)

data class TabletSubmitSignatureRequest(
    /** SHA-256 (hex) computed by the tablet over the PDF bytes it displayed. */
    val documentSha256: String,
    val challenge: String,
    val declarationAccepted: Boolean,
    val declarationAcceptedAt: Instant? = null,
    /** PNG with alpha channel (transparent background), base64. */
    val signatureImageBase64: String
)

data class TabletDeclineRequest(
    val reason: String? = null
)

data class TabletSubmitSignatureResponse(
    val requestId: String,
    val status: String,
    val sealApplied: Boolean,
    val timestampApplied: Boolean
)
