-- Fix for audit_logs_action_check constraint
-- The following lead-specific AuditAction values were added to the enum
-- but never included in the DB constraint, causing silent audit log failures:
--   LEAD_COMMENT_ADDED, LEAD_COMMENT_DELETED, LEAD_CUSTOMER_ANSWERED,
--   LEAD_SPLIT, LEAD_MERGED, LEAD_ACKNOWLEDGED
--
-- Run: psql -U postgres -d detailing_crm -f fix-audit-logs-action-constraint-lead-actions.sql

ALTER TABLE audit_logs
DROP CONSTRAINT IF EXISTS audit_logs_action_check;

ALTER TABLE audit_logs
ADD CONSTRAINT audit_logs_action_check
CHECK (action IN (
    -- CRUD
    'CREATE', 'UPDATE', 'DELETE',
    -- Status
    'STATUS_CHANGE',
    -- Sub-entity
    'PHOTO_ADDED', 'PHOTO_DELETED', 'DOCUMENT_ADDED',
    'COMMENT_ADDED', 'COMMENT_UPDATED', 'COMMENT_DELETED',
    'NOTE_ADDED', 'NOTE_UPDATED', 'NOTE_DELETED',
    -- Visit
    'SERVICE_ADDED', 'SERVICE_UPDATED', 'SERVICE_REMOVED', 'SERVICES_UPDATED',
    'VISIT_CONFIRMED', 'VISIT_CANCELLED', 'VISIT_COMPLETED', 'VISIT_REJECTED',
    'VISIT_MARKED_READY', 'VISIT_ARCHIVED', 'VISIT_DELETED',
    -- Appointment
    'APPOINTMENT_CANCELLED', 'APPOINTMENT_RESTORED', 'APPOINTMENT_DELETED',
    'APPOINTMENT_CONVERTED', 'APPOINTMENT_ABANDONED',
    -- Protocol / Consent
    'PROTOCOL_GENERATED', 'PROTOCOL_SIGNED',
    'CONSENT_GRANTED', 'CONSENT_REVOKED',
    -- Lead
    'LEAD_CONVERTED', 'LEAD_ABANDONED', 'LEAD_CONFIRMED', 'LEAD_COMPLETED',
    'LEAD_LOST', 'LEAD_NO_SHOW', 'LEAD_APPOINTMENT_CREATED',
    'LEAD_USER_ASSIGNED', 'LEAD_CUSTOMER_ASSIGNED', 'LEAD_LOST_REASON_UPDATED',
    'LEAD_QUOTE_UPDATED', 'LEAD_COMMENT_UPDATED', 'LEAD_ESTIMATION_COMPLETED',
    'LEAD_COMMENT_ADDED', 'LEAD_COMMENT_DELETED', 'LEAD_CUSTOMER_ANSWERED',
    'LEAD_SPLIT', 'LEAD_MERGED', 'LEAD_ACKNOWLEDGED',
    -- Inbound
    'CALL_ACCEPTED', 'CALL_REJECTED',
    -- Vehicle
    'OWNER_ADDED', 'OWNER_REMOVED', 'APPOINTMENT_ADDED', 'VISIT_ADDED',
    -- Company
    'COMPANY_UPDATED', 'COMPANY_DELETED',
    -- Finance
    'DOCUMENT_ISSUED', 'DOCUMENT_STATUS_CHANGED', 'DOCUMENT_NUMBER_UPDATED',
    'DOCUMENT_DELETED', 'DOCUMENT_RESTORED', 'CASH_ADJUSTED',
    -- Employee
    'EMPLOYEE_TERMINATED', 'CONTRACT_CREATED', 'CONTRACT_ENDED', 'COMPENSATION_SET',
    'WORK_TIME_LOGGED', 'WORK_TIME_APPROVED', 'WORK_TIME_REJECTED', 'WORK_TIME_PERIOD_SAVED',
    'WORK_TIME_ENTRY_DELETED', 'LEAVE_REQUESTED', 'LEAVE_APPROVED', 'LEAVE_REJECTED',
    'LEAVE_CANCELLED', 'PAYROLL_GENERATED', 'PAYROLL_CONFIRMED', 'PAYROLL_PAID',
    'BONUS_ADDED', 'BONUS_DELETED',
    -- Security
    'CROSS_TENANT_ACCESS_ATTEMPT', 'LOGIN_FAILURE', 'LOGIN_SUCCESS', 'ACCOUNT_LOCKED'
));

-- Verify
SELECT conname, pg_get_constraintdef(oid)
FROM pg_constraint
WHERE conname = 'audit_logs_action_check';
