-- Opcjonalne czyszczenie role_permissions po konsolidacji katalogu uprawnień (drzewo v2).
--
-- Aplikacja NIE wymaga tego skryptu: stare kody sa tlumaczone w locie przy odczycie
-- (Permission.fromStoredCode). Skrypt jedynie czysci tabele trwale, zeby nie zalegaly
-- martwe kody. Pelna mapa i uzasadnienia: Permission.kt (legacyAliases).

BEGIN;

UPDATE role_permissions
SET permission = CASE permission
    -- wizyty: wezly drzewa sprzed konsolidacji
    WHEN 'VISITS_VIEW_DETAILS'          THEN 'VISITS_VIEW'
    WHEN 'VISITS_EDIT'                  THEN 'VISITS_CREATE'
    WHEN 'VISITS_SERVICES_VIEW'         THEN 'VISITS_VIEW'
    WHEN 'VISITS_SERVICES_MANAGE'       THEN 'VISITS_CREATE'
    WHEN 'VISITS_COMMENTS_VIEW'         THEN 'VISITS_VIEW'
    WHEN 'VISITS_COMMENTS_ADD'          THEN 'VISITS_VIEW'
    WHEN 'VISITS_NOTES_ADD'             THEN 'VISITS_VIEW'
    WHEN 'VISITS_MEDIA_VIEW'            THEN 'VISITS_VIEW'
    WHEN 'VISITS_MEDIA_UPLOAD'          THEN 'VISITS_VIEW'
    WHEN 'VISITS_DOCUMENTS_VIEW'        THEN 'VISITS_DOCUMENTS_MANAGE'
    WHEN 'VISITS_DOCUMENTS_CREATE'      THEN 'VISITS_DOCUMENTS_MANAGE'
    WHEN 'VISITS_DOCUMENTS_SIGN'        THEN 'VISITS_DOCUMENTS_MANAGE'
    -- wizyty: era plaskiej listy
    WHEN 'VISITS_VIEW_PRICES'           THEN 'VISITS_SERVICE_PRICES_VIEW'
    WHEN 'VISITS_VIEW_COMMENTS'         THEN 'VISITS_VIEW'
    WHEN 'VISITS_ADD_COMMENT'           THEN 'VISITS_VIEW'
    WHEN 'DOCUMENTS_VIEW'               THEN 'VISITS_DOCUMENTS_MANAGE'
    WHEN 'DOCUMENTS_CREATE'             THEN 'VISITS_DOCUMENTS_MANAGE'
    WHEN 'DOCUMENTS_SIGN'               THEN 'VISITS_DOCUMENTS_MANAGE'
    WHEN 'DOCUMENTS_MANAGE'             THEN 'VISITS_DOCUMENTS_MANAGE'
    WHEN 'GALLERY_VIEW'                 THEN 'VISITS_VIEW'
    WHEN 'GALLERY_UPLOAD'               THEN 'VISITS_VIEW'
    WHEN 'GALLERY_DELETE'               THEN 'VISITS_MEDIA_DELETE'
    -- kalendarz = wizyty
    WHEN 'CALENDAR_VIEW'                THEN 'VISITS_VIEW'
    WHEN 'CALENDAR_MANAGE'              THEN 'VISITS_CREATE'
    -- pojazdy = wizyty (odczyt/zapis) i klienci (usuwanie)
    WHEN 'VEHICLES_VIEW'                THEN 'VISITS_VIEW'
    WHEN 'VEHICLES_CREATE'              THEN 'VISITS_CREATE'
    WHEN 'VEHICLES_EDIT'                THEN 'VISITS_CREATE'
    WHEN 'VEHICLES_DELETE'              THEN 'CUSTOMERS_DELETE'
    -- klienci
    WHEN 'CUSTOMERS_VIEW_PERSONAL_DATA' THEN 'CUSTOMERS_VIEW'
    WHEN 'CUSTOMERS_CREATE'             THEN 'CUSTOMERS_MANAGE'
    WHEN 'CUSTOMERS_EDIT'               THEN 'CUSTOMERS_MANAGE'
    -- komunikacja
    WHEN 'COMMUNICATION_VIEW_LOGS'      THEN 'CUSTOMERS_VIEW'
    WHEN 'COMMUNICATION_SEND_SMS'       THEN 'COMMUNICATION_SEND'
    WHEN 'COMMUNICATION_SEND_EMAIL'     THEN 'COMMUNICATION_SEND'
    -- finanse
    WHEN 'FINANCE_VIEW_INVOICES'        THEN 'FINANCE_INVOICES'
    WHEN 'FINANCE_CREATE_INVOICE'       THEN 'FINANCE_INVOICES'
    -- pracownicy
    WHEN 'EMPLOYEES_MANAGE_ACCOUNTS'    THEN 'EMPLOYEES_MANAGE'
    WHEN 'EMPLOYEES_VIEW_PAYROLL'       THEN 'EMPLOYEES_PAYROLL'
    WHEN 'EMPLOYEES_MANAGE_PAYROLL'     THEN 'EMPLOYEES_PAYROLL'
    -- zadania / leady
    WHEN 'TASKS_ASSIGN'                 THEN 'TASKS_MANAGE'
    WHEN 'LEADS_VIEW'                   THEN 'LEADS_MANAGE'
END
WHERE permission IN (
    'VISITS_VIEW_DETAILS','VISITS_EDIT','VISITS_SERVICES_VIEW','VISITS_SERVICES_MANAGE',
    'VISITS_COMMENTS_VIEW','VISITS_COMMENTS_ADD','VISITS_NOTES_ADD',
    'VISITS_MEDIA_VIEW','VISITS_MEDIA_UPLOAD',
    'VISITS_DOCUMENTS_VIEW','VISITS_DOCUMENTS_CREATE','VISITS_DOCUMENTS_SIGN',
    'VISITS_VIEW_PRICES','VISITS_VIEW_COMMENTS','VISITS_ADD_COMMENT',
    'DOCUMENTS_VIEW','DOCUMENTS_CREATE','DOCUMENTS_SIGN','DOCUMENTS_MANAGE',
    'GALLERY_VIEW','GALLERY_UPLOAD','GALLERY_DELETE',
    'CALENDAR_VIEW','CALENDAR_MANAGE',
    'VEHICLES_VIEW','VEHICLES_CREATE','VEHICLES_EDIT','VEHICLES_DELETE',
    'CUSTOMERS_VIEW_PERSONAL_DATA','CUSTOMERS_CREATE','CUSTOMERS_EDIT',
    'COMMUNICATION_VIEW_LOGS','COMMUNICATION_SEND_SMS','COMMUNICATION_SEND_EMAIL',
    'FINANCE_VIEW_INVOICES','FINANCE_CREATE_INVOICE',
    'EMPLOYEES_MANAGE_ACCOUNTS','EMPLOYEES_VIEW_PAYROLL','EMPLOYEES_MANAGE_PAYROLL',
    'TASKS_ASSIGN','LEADS_VIEW'
);

-- EMPLOYEES_VIEW nie ma nastepcy — katalog wspolpracownikow nie jest uprawnieniem.
DELETE FROM role_permissions WHERE permission = 'EMPLOYEES_VIEW';

-- Mapowanie wielu starych kodow na jeden nowy zostawia duplikaty — usun je.
DELETE FROM role_permissions a
USING role_permissions b
WHERE a.ctid < b.ctid
  AND a.role_id = b.role_id
  AND a.permission = b.permission;

COMMIT;
