services:
  detailing-crm-backend:
    image: ${ENV_DETAILING_CRM_BACKEND_IMAGE}
    container_name: ${DETAILING_CRM_BACKEND_CONTAINER_NAME}
    ports:
      - '${ENV_DETAILING_CRM_BACKEND_EXTERNAL_PORT}:8080'
      - '${ENV_DETAILING_CRM_BACKEND_DEBUG_PORT}:5005'
    restart: always
    environment:
      DB_ADDR: ${ENV_DB_ADDR}
      DB_PORT: ${ENV_DB_PORT}
      DB_NAME: ${ENV_DB_NAME}
      DB_USER: ${ENV_DB_USER}
      DB_PASSWORD: ${ENV_DB_PASSWORD}
      REDIS_ADDR: ${ENV_REDIS_ADDR}
      REDIS_PORT: ${ENV_REDIS_PORT}
      S3_ACCESS_KEY: ${ENV_S3_ACCESS_KEY}
      S3_SECRET_KEY: ${ENV_S3_SECRET_KEY}
      GITHUB_ACTOR: ${ENV_GITHUB_ACTOR}
      GITHUB_TOKEN: ${ENV_GITHUB_TOKEN}
      OPENAI_API_KEY: ${ENV_OPENAI_API_KEY}
      SMSAPI_OAUTH_TOKEN: ${ENV_SMSAPI_OAUTH_TOKEN}
      CLOUDFLARE_EMAIL_WEBHOOK_TOKEN: ${ENV_CLOUDFLARE_EMAIL_WEBHOOK_TOKEN}
      APP_ENV: ${ENV_APP_ENV:-production}
      GUS_API_KEY: ${ENV_GUS_API_KEY}
      ENV_GUS_ENDPOINT_URL: ${ENV_GUS_ENDPOINT_URL}
      MAIL_USERNAME: ${ENV_MAIL_USERNAME}
      MAIL_PASSWORD: ${ENV_MAIL_PASSWORD}
      MAIL_HOST: ${ENV_MAIL_HOST}
      RAPIDAPI_KEY: ${ENV_RAPIDAPI_KEY}
      MAILBOX_ENCRYPTION_KEY: ${ENV_MAILBOX_ENCRYPTION_KEY}
      REPORT_PROBLEM_EMAIL: ${ENV_REPORT_PROBLEM_EMAIL}
      VAPID_PUBLIC_KEY: ${ENV_VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${ENV_VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${ENV_VAPID_SUBJECT}
    depends_on:
      - redis
    networks:
      - network

  redis:
    image: redis:alpine
    networks:
      - network

networks:
  network:
    name: ${ENV_NETWORK}
    external: true
