package pl.detailing.crm.employee.payroll

import pl.detailing.crm.shared.*
import java.time.YearMonth

data class GeneratePayrollCommand(
    val studioId: StudioId,
    val userId: UserId,
    val userName: String?,
    val employeeId: EmployeeId,
    val period: YearMonth,
    /**
     * Gross revenue generated by the employee in this period.
     * Required to calculate [ComponentType.PERCENTAGE_OF_REVENUE] components
     * with [CalculationBase.GROSS_REVENUE].
     */
    val revenueGrossCents: Long?,
    /**
     * Net revenue generated by the employee in this period.
     * Required to calculate [ComponentType.PERCENTAGE_OF_REVENUE] components
     * with [CalculationBase.NET_REVENUE].
     */
    val revenueNetCents: Long?,
    val notes: String?
)
