-- Gallery performance: pre-generated thumbnails + sort index.
--
-- thumbnail_file_id holds the S3 key of the resized thumbnail generated by
-- ThumbnailBackfillJob; NULL means "not generated yet" and the gallery falls
-- back to the original. uploaded_at indexes support the SQL-side
-- ORDER BY uploaded_at in the gallery query.
--
-- IF NOT EXISTS: dev environments run with ddl-auto=update, which may have
-- already added these columns/indexes from the entity mappings.

ALTER TABLE visit_photos ADD COLUMN IF NOT EXISTS thumbnail_file_id VARCHAR(500);
ALTER TABLE vehicle_photos ADD COLUMN IF NOT EXISTS thumbnail_file_id VARCHAR(500);
ALTER TABLE batch_order_entry_photos ADD COLUMN IF NOT EXISTS thumbnail_file_id VARCHAR(500);

CREATE INDEX IF NOT EXISTS idx_visit_photos_uploaded_at ON visit_photos (uploaded_at);
CREATE INDEX IF NOT EXISTS idx_vehicle_photos_uploaded_at ON vehicle_photos (uploaded_at);
CREATE INDEX IF NOT EXISTS idx_batch_order_photos_uploaded_at ON batch_order_entry_photos (uploaded_at);
