package pl.detailing.crm.comms.send

import jakarta.activation.DataHandler
import jakarta.mail.Message
import jakarta.mail.Part
import jakarta.mail.Session
import jakarta.mail.Transport
import jakarta.mail.internet.InternetAddress
import jakarta.mail.internet.MimeBodyPart
import jakarta.mail.internet.MimeMessage
import jakarta.mail.internet.MimeMultipart
import jakarta.mail.internet.MimeUtility
import jakarta.mail.util.ByteArrayDataSource
import org.jsoup.Jsoup
import org.jsoup.nodes.TextNode
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service
import pl.detailing.crm.mailbox.infrastructure.MailAccountEntity
import pl.detailing.crm.mailbox.infrastructure.MailboxEncryptionService
import pl.detailing.crm.shared.ValidationException
import java.util.Date
import java.util.Properties
import java.util.UUID

data class OutgoingMail(
    val to: List<String>,
    val cc: List<String> = emptyList(),
    val subject: String,
    val bodyHtml: String,
    val inReplyTo: String? = null,
    val references: List<String> = emptyList(),
    val attachments: List<OutgoingAttachment> = emptyList()
)

/**
 * Sends mail from the studio's own mailbox over SMTP, with RFC 5322 threading headers.
 * The Message-ID is generated by us and persisted before the message leaves, so the
 * copy later ingested from the Sent folder dedupes against the local record.
 *
 * The transactional [pl.detailing.crm.email.provider.javamail.JavaMailProvider] cannot
 * be reused: it is bound to one global SMTP account and hardcodes the sender.
 */
@Service
class AccountMailSender(
    private val encryptionService: MailboxEncryptionService
) {
    private val log = LoggerFactory.getLogger(javaClass)

    /** Message-ID without angle brackets — stored as-is in comm_messages.message_id_hdr. */
    fun newMessageId(account: MailAccountEntity): String {
        val domain = account.emailAddress.substringAfter('@', "").ifBlank { "localhost" }
        return "${UUID.randomUUID()}@$domain"
    }

    fun send(account: MailAccountEntity, messageId: String, mail: OutgoingMail) {
        val message = compose(account, messageId, mail)
        val password = passwordOf(account)
        Transport.send(message, account.emailAddress, password)
        log.info(
            "[COMMS] Wysłano wiadomość | account={} to={} messageId={}",
            account.emailAddress, mail.to.joinToString(","), messageId
        )
    }

    /** Builds the exact MimeMessage — also used by the outbox to APPEND a copy to Sent. */
    fun compose(account: MailAccountEntity, messageId: String, mail: OutgoingMail): MimeMessage {
        val smtpHost = account.smtpHost?.takeIf { it.isNotBlank() }
            ?: throw ValidationException("Skrzynka ${account.emailAddress} nie ma skonfigurowanego serwera SMTP")
        val smtpPort = account.smtpPort ?: DEFAULT_SUBMISSION_PORT

        val props = Properties().apply {
            put("mail.smtp.host", smtpHost)
            put("mail.smtp.port", smtpPort.toString())
            put("mail.smtp.auth", "true")
            if (smtpPort == SMTPS_PORT) {
                put("mail.smtp.ssl.enable", "true")
            } else {
                put("mail.smtp.starttls.enable", "true")
            }
            put("mail.smtp.connectiontimeout", "10000")
            put("mail.smtp.timeout", "20000")
            put("mail.smtp.writetimeout", "20000")
        }

        val session = Session.getInstance(props)
        // Jakarta Mail generates its own Message-ID on save; override it so the id we persisted wins.
        val message = object : MimeMessage(session) {
            override fun updateMessageID() {
                setHeader("Message-ID", "<$messageId>")
            }
        }

        message.setFrom(InternetAddress(account.emailAddress))
        message.setRecipients(Message.RecipientType.TO, mail.to.joinToString(",").let { InternetAddress.parse(it) })
        if (mail.cc.isNotEmpty()) {
            message.setRecipients(Message.RecipientType.CC, InternetAddress.parse(mail.cc.joinToString(",")))
        }
        message.setSubject(mail.subject, "UTF-8")
        message.sentDate = Date()
        mail.inReplyTo?.let { message.setHeader("In-Reply-To", "<$it>") }
        if (mail.references.isNotEmpty()) {
            message.setHeader("References", mail.references.joinToString(" ") { "<$it>" })
        }
        message.setContent(buildContent(mail))
        message.saveChanges()
        return message
    }

    /**
     * Struktura MIME:
     *
     *   multipart/mixed
     *   ├─ multipart/alternative
     *   │  ├─ text/plain   (treść bez znaczników — dla filtrów antyspamowych i czytników)
     *   │  └─ text/html    (to, co użytkownik napisał i sformatował)
     *   └─ application/…   (załączniki, po jednym na część)
     *
     * Część tekstowa jest zawsze, także bez załączników: wiadomość z samym HTML-em
     * ląduje w spamie częściej niż z alternatywą tekstową, a koszt to jedno przejście
     * jsoupem.
     */
    private fun buildContent(mail: OutgoingMail): MimeMultipart {
        val alternative = MimeMultipart("alternative").apply {
            addBodyPart(MimeBodyPart().apply { setText(htmlToPlainText(mail.bodyHtml), "UTF-8") })
            addBodyPart(MimeBodyPart().apply { setContent(mail.bodyHtml, "text/html; charset=UTF-8") })
        }
        if (mail.attachments.isEmpty()) return alternative

        return MimeMultipart("mixed").apply {
            addBodyPart(MimeBodyPart().apply { setContent(alternative) })
            mail.attachments.forEach { attachment ->
                addBodyPart(
                    MimeBodyPart().apply {
                        dataHandler = DataHandler(ByteArrayDataSource(attachment.content, attachment.contentType))
                        // RFC 2047: polskie znaki w nazwie pliku muszą być zakodowane,
                        // inaczej część klientów pokazuje „?????.pdf".
                        fileName = MimeUtility.encodeText(attachment.fileName, "UTF-8", null)
                        disposition = Part.ATTACHMENT
                    }
                )
            }
        }
    }

    /** Wersja tekstowa treści HTML: bloki jako osobne linie, listy z myślnikiem, odnośniki z adresem. */
    private fun htmlToPlainText(html: String): String {
        val document = Jsoup.parse(html)
        // Podmiana, nie doklejenie: nowsze jsoupy same oddają <br> jako nową linię
        // w wholeText(), a z doklejonym "\n" wychodziłyby dwie.
        document.select("br").forEach { it.replaceWith(TextNode("\n")) }
        document.select("li").forEach { it.prepend("- ") }
        document.select("p, div, li, tr, h1, h2, h3, h4, h5, h6, blockquote").forEach { it.append("\n") }
        document.select("a[href]").forEach { anchor ->
            val href = anchor.attr("href")
            if (href.isNotBlank() && anchor.text().trim() != href) anchor.append(" ($href)")
        }
        return document.body().wholeText()
            .replace('\u00a0', ' ')
            .lines()
            .joinToString("\n") { it.trimEnd() }
            .replace(Regex("\n{3,}"), "\n\n")
            .trim()
    }

    fun passwordOf(account: MailAccountEntity): String =
        account.encryptedPassword?.let { encryptionService.decrypt(it) }
            ?: throw ValidationException("Skrzynka ${account.emailAddress} nie ma zapisanych poświadczeń")

    companion object {
        const val DEFAULT_SUBMISSION_PORT = 587
        const val SMTPS_PORT = 465
    }
}
